//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipamentos()
        {
            this.Transacoes = new HashSet<Transacoes>();
        }
    
        public int Id { get; set; }
        public string Equipamento { get; set; }
        public string Modelo { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public string Local { get; set; }
        public string Armario { get; set; }
        public Nullable<int> Prateleira { get; set; }
        public string SistOper { get; set; }
        public string AplicativoInstalado { get; set; }
        public string SistemaAutomação { get; set; }
        public string Status { get; set; }
        public string PC { get; set; }
        public string RC { get; set; }
        public string ItemRC { get; set; }
        public string NF { get; set; }
        public Nullable<System.DateTime> DataGarantia { get; set; }
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacoes> Transacoes { get; set; }
    }
}
