//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacoes
    {
        public int Id { get; set; }
        public string Transacao { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Local { get; set; }
        public int IdEquipamento { get; set; }
    
        public virtual Equipamentos Equipamentos { get; set; }
    }
}
